version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./facturas.db:/app/facturas.db
      - ./temp_pdfs:/app/temp_pdfs
      - ./temp_qr:/app/temp_qr
      - ./logs:/app/logs
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
